image: cgswong/aws

pipelines:
  branches:
    master:
      - step:
          name: Deploy to Adysis Prebid AWS S3
          deployment: Adysis Prebid AWS S3
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - aws s3 --region "us-east-1" sync prebid/ s3://adysis-ad-delivery-js --cache-control "public, max-age=31536000" --delete
      - step:
         name: Deploy to Adysis Prebid Google Bucket
         deployment: Adysis Prebid Google Bucket
         # trigger: manual  # Uncomment to make this a manual deployment.
         script:       
            - pipe: atlassian/google-cloud-storage-deploy:0.4.0
              variables:
                KEY_FILE: '<string>'
                PROJECT: 'Adysis'
                BUCKET: 'adysis'
                SOURCE: '.'
                # CACHE_CONTROL: '<string>' # Optional.
                # CONTENT_DISPOSITION: '<string>' # Optional.
                # CONTENT_ENCODING: '<string>' # Optional.
                # CONTENT_LANGUAGE: '<string>' # Optional.
                # CONTENT_TYPE: '<string>' # Optional.
                # ACL: '<string>' # Optional.
                # STORAGE_CLASS: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
