image: cgswong/aws

pipelines:
  branches:
    master:
      - step:
          name: Deploy to Adysis Prebid Testing
          deployment: Adysis Prebid Testing
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - aws s3 --region "us-east-1" sync prebid/ s3://adysis-ad-delivery-js --cache-control "public, max-age=31536000" --delete          