image: cgswong/aws

pipelines:
  branches:
    master:
      - step:
          script:
            - aws s3 --region "us-east-1" sync public/ s3://adysis-ad-delivery-js--cache-control "public, max-age=14400" --delete